---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
```{r load libraries}
library(dplyr)
library(ggplot2)
library(vroom)
```

## Loading and preprocessing the data
```{r}
raw <- vroom("activity.zip")
str(raw)
```


## What is mean total number of steps taken per day?
```{r}
total_steps <- raw %>% group_by(date) %>% summarise(tot_steps = sum(steps, na.rm = TRUE))
ggplot(total_steps, aes(x=tot_steps)) + geom_histogram(binwidth = 1000)
mean(total_steps$tot_steps)
median(total_steps$tot_steps)
```



## What is the average daily activity pattern?
```{r}
interval_steps <- raw %>% group_by(interval) %>% summarise(int_steps = mean(steps, na.rm = TRUE))
ggplot(data=interval_steps, aes(x=interval, y=int_steps)) + geom_line()
interval_steps[which.max(interval_steps$int_steps),]
```


## Imputing missing values
```{r}
raw %>% count(is.na(steps))

imputed_data <- as.data.frame(raw)
imputed_data$imputed <- is.na(imputed_data$steps)

tmp <- imputed_data[c(imputed_data$imputed),] %>% left_join(interval_steps, by="interval")

imputed_data[c(imputed_data$imputed),]$steps <- tmp$int_steps
imputed_data %>% count(is.na(steps))

total_steps2 <- imputed_data %>% group_by(date) %>% summarise(tot_steps = sum(steps, na.rm = TRUE))
ggplot(total_steps2, aes(x=tot_steps)) + geom_histogram(binwidth = 1000)
mean(total_steps2$tot_steps)
median(total_steps2$tot_steps)
```


## Are there differences in activity patterns between weekdays and weekends?
```{r}
imputed_data$weekdays
interval_steps <- imputed_data %>% group_by(interval) %>% summarise(int_steps = mean(steps, na.rm = TRUE))
ggplot(data=interval_steps, aes(x=interval, y=int_steps)) + geom_line()
```